### ISSUE TITLE
Results are not very good

### ISSUE THREAD

**Issue by mnpenner** [Ucas-HaoranWei/GOT-OCR2.0#115]
Hi, thank you for releasing this and sharing it with the world.

I was trying it on some hand-written images I have, and the results I'm getting are not very good so far, unfortunately.

Here's an example image:

![image](https://github.com/user-attachments/assets/9e237137-852d-4f84-bbfb-42fabedcd2e2)

The output is

```
To櫒Michee|
```

Which is obviously not correct.

This one is better:

![image](https://github.com/user-attachments/assets/d4bb0cc5-dc0b-44ab-b17a-707447361918)

```
lo:Michael
THANKS for
the picture
of you!
From:Ryan
```

It wasn't able to error-correct the very first letter but that's not bad.

This one it struggles with quite a bit too:

![image](https://github.com/user-attachments/assets/e5de2502-e72b-4479-9f33-0c67865d0f98)

```
\title{
helle, \\ woud!
}
```

I'm running these with

```sh
python3 GOT/demo/run_ocr_2.0.py --model-name /mnt/data/GOT-OCR2_0 --type format --image-file /mnt/data/lettering-hello-world-vector-24929175.jpg
```

Maybe I'm doing something wrong or the model needs some tweaking yet. Pasting these same images into Chat GPT-4o gives perfect results.

**Comment by Ucas-HaoranWei** [comment]
Oh, I did not train artistic character data to train the model, please refer to the paper for the data used for training. Recommend using your data to fine-tune GOT.

**Comment by mnpenner** [comment]
Thanks for the tip. I might give it a go!
