### ISSUE TITLE
ModuleNotFoundError: No module named 'GOT'

### ISSUE THREAD

**Issue by Gao-Jack-byte** [Ucas-HaoranWei/GOT-OCR2.0#131]
执行测试指令报错，请帮忙看下是哪里配置的问题

![企业微信截图_6f948357-7a36-4cbe-8ebe-415f122e0f17](https://github.com/user-attachments/assets/edc33207-3cea-448a-842a-6c7468e27894)
![企业微信截图_3207d2a5-163a-4da1-9683-c054446b1a6e](https://github.com/user-attachments/assets/1933386f-369a-4494-9013-8d9aa8a07aaf)
![企业微信截图_d45b7978-b5f9-49c4-83b4-ef2c02033bc9](https://github.com/user-attachments/assets/6321ea96-9bd5-4ec7-9082-b2058560f16f)

**Comment by wuhaotju** [comment]
咋解决的 兄弟

**Comment by yeongjet** [comment]
`pip install -e .`
