### ISSUE TITLE
License incorrectly specified

### ISSUE THREAD

**Issue by markap14** [Ucas-HaoranWei/GOT-OCR2.0#133]
The readme states:

```
[![Code License](https://img.shields.io/badge/Code%20License-Apache_2.0-green.svg)](https://github.com/tatsu-lab/stanford_alpaca/blob/main/LICENSE)
[![Data License](https://img.shields.io/badge/Data%20License-CC%20By%20NC%204.0-red.svg)](https://github.com/tatsu-lab/stanford_alpaca/blob/main/DATA_LICENSE)

**Usage and License Notices**: The data, code, and checkpoint are intended and licensed for research use only. They are also restricted to use that follow the license agreement of Vary. 
```

So it declares the Code to be licensed as Apache 2.0, and then immediately declares it to be "intended and licensed for research use only," which is antithetical to the Apache 2.0 license. Is the code intended to be Apache Licensed, or for research use only?

It appears that the model weights on HuggingFace are also declared to be Apache 2.0 Licensed. Is that the correct license for the model?

**Comment by Ucas-HaoranWei** [comment]
I change the license, please use the model more casually.

**Comment by markap14** [comment]
Thanks @Ucas-HaoranWei . I will go ahead and close the Issue then.
