### ISSUE TITLE
swift微调出错：ms-swift ValueError: model_type: 'got-ocr2' is not registered

### ISSUE THREAD

**Issue by Li-Jicheng** [Ucas-HaoranWei/GOT-OCR2.0#136]
可以问一下微调模型我们支持的ms-swift版本是多少吗？遇到了这个error。这是ms-swift的问题还是transformers的问题呢？

    raise ValueError(f"model_type: '{self.model_type}' is not registered. " + error_msg)
ValueError: model_type: 'got-ocr2' is not registered

我的 ms-swift
Version: 2.4.2.post2
transformers
Version: 4.44.2

**Comment by Ucas-HaoranWei** [comment]
你应该是load的不是modelscope的权重

**Comment by Li-Jicheng** [comment]
我是在hugging face 下载的权重，完整错误信息大概是这样。请问是需要在modelscope下载权重吗
<img width="1048" alt="Screenshot 2024-10-18 at 16 58 00" src="https://github.com/user-attachments/assets/16ceb787-cc22-41c9-bbc3-b10b9d117ea5">

**Comment by Li-Jicheng** [comment]
我的微调指令
swift sft \
--model_type got-ocr2 \
--model_id_or_path ../huggingface.co/ucaslcl/GOT-OCR2_0 \
--sft_type full \
--dataset toy_train.jsonl
--num_train_epochs 1 \
--save_total_limit 10 \
--dtype bf16 \
--gradient_checkpointing true \
--save_only_model true \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 1 \
--gradient_accumulation_steps 8 \
--learning_rate 1e-5 \
--weight_decay 0.1 \
--adam_beta2 0.95 \
--warmup_ratio 0.01 \
--freeze_vit true \
--system "你是一位OCR专家" \
--lr_scheduler_type "cosine" \
--logging_steps 1 \
--save_strategy epoch

**Comment by Ucas-HaoranWei** [comment]
得用modelscope的权重，因为是成套的

**Comment by Li-Jicheng** [comment]
可以辛苦发一下modelscope的权重下载link吗？我之前是在这里下载的https://huggingface.co/ucaslcl/GOT-OCR2_0

**Comment by Li-Jicheng** [comment]
install lastest ms-swift fixed my issue:ms-swift 2.5.0.post1
thanks for answering

**Comment by sisimbisim222** [comment]
Is this the same as this? 
```
 File "/opt/conda/lib/python3.11/site-packages/swift/llm/model/register.py", line 400, in _get_model_info
    raise ValueError(f"model_type: '{model_type}' not in {list(MODEL_MAPPING.keys())}")
ValueError: model_type: 'got-ocr2' not in ['emu3_gen', 'emu3_chat', 'baichuan', 'baichuan_m1', 'baichuan2', 'modern_bert', 'modern_bert_gte', 'bert', 'chatglm2', 'chatglm3', 'glm4', 'longwriter_llama3_1', 'codegeex4', 'glm4v', 'cogvlm', 'cogagent_chat', 'cogagent_vqa', 'cogvlm2', 'cogvlm2_video', 'glm_edge', 'glm_edge_v', 'qwen', 'modelscope_agent', 'qwen_audio', 'qwen_vl', 'qwen2', 'qwen2_5', 'qwen2_5_math', 'qwen2_moe', 'qwen2_vl', 'qvq', 'qwen2_5_vl', 'qwen2_5_omni', 'qwen2_audio', 'marco_o1', 'qwq_preview', 'qwq', 'ovis1_6', 'ovis1_6_llama3', 'ovis2', 'qwen2_reward', 'qwen2_5_prm', 'qwen2_5_math_reward', 'codefuse_qwen', 'codefuse_codegeex2', 'codefuse_codellama', 'deepseek', 'deepseek_moe', 'deepseek_v2', 'deepseek_v2_5', 'deepseek_vl', 'deepseek_janus', 'deepseek_janus_pro', 'deepseek_vl2', 'deepseek_r1', 'deepseek_r1_distill', 'moonlight', 'paligemma', 'gemma', 'gemma2
```

>>> import swift
>>> swift.__version__
'3.3.0.dev0'
