### ISSUE TITLE
在fine-tuning之后，如何使用PeftModel启动加载 LoRA 微调权重，直接启动提示失败 only torch.nn.Linear and Conv1D are supported？

### ISSUE THREAD

**Issue by evanlin88** [Ucas-HaoranWei/GOT-OCR2.0#144]
# 启动LoRA 代码
from GOT.model import *
from transformers import AutoTokenizer
from transformers import TextStreamer
from peft import PeftModel
import io
import os
import argparse

parser = argparse.ArgumentParser()
args = argparse.Namespace()
args.model_name = "/data/model/got_ocr2"
args.lora_model_path = '/data/swift-fine-tuning/output/got-ocr2/v2-20241021-161234/checkpoint-1000'
args.type = "format"
args.box = ''
args.color = ''

disable_torch_init()
model_name = os.path.expanduser(args.model_name)
lora_model_path = os.path.expanduser(args.lora_model_path)

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)

# 加载 LoRA 微调权重
model = PeftModel.from_pretrained(model, lora_model_path)

**#  启动失败 ，异常信息**
Traceback (most recent call last):
  File "/data/got-ocr/GOT-OCR2.0-main/GOT-OCR-2.0-master/GOT/demo/run_ocr_server.py", line 48, in <module>
    model = PeftModel.from_pretrained(model, lora_model_path)
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 270, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 893, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/peft_model.py", line 112, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter
    self._find_and_replace(adapter_name)
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target)
  File "/data/anaconda3/envs/got/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module
    raise ValueError(
ValueError: Target module ModuleList(
  (0-23): 24 x Qwen2DecoderLayer(
    (self_attn): Qwen2SdpaAttention(
      (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
      (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
      (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
      (o_proj): Linear(in_features=1024, out_features=1024, bias=False)
      (rotary_emb): Qwen2RotaryEmbedding()
    )
    (mlp): Qwen2MLP(
      (gate_proj): Linear(in_features=1024, out_features=2816, bias=False)
      (up_proj): Linear(in_features=1024, out_features=2816, bias=False)
      (down_proj): Linear(in_features=2816, out_features=1024, bias=False)
      (act_fn): SiLU()
    )
    (input_layernorm): Qwen2RMSNorm()
    (post_attention_layernorm): Qwen2RMSNorm()
  )
) is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.

# model_name = "/data/model/got_ocr2" 目录结构
-rw-r--r--  1 root root        986 10月 18 18:22 config.json
-rw-r--r--  1 root root          2 10月 18 18:22 configuration.json
-rw-r--r--  1 root root        117 10月 18 18:22 generation_config.json
-rw-r--r--  1 root root      16106 10月 18 19:41 got_vision_b.py
-rw-r--r--  1 root root      33771 10月 18 19:41 modeling_GOT.py
-rw-r--r--  1 root root 1432121416 10月 18 19:41 model.safetensors
-rw-r--r--  1 root root    2561218 10月 18 18:22 qwen.tiktoken
-rw-r--r--  1 root root       4103 10月 18 19:41 README.md
-rw-r--r--  1 root root       1992 10月 18 18:22 render_tools.py
-rw-r--r--  1 root root        149 10月 18 19:41 special_tokens_map.json
-rw-r--r--  1 root root       9470 10月 18 18:22 tokenization_qwen.py
-rw-r--r--  1 root root        300 10月 18 19:41 tokenizer_config.json

# lora_model_path = '/data/swift-fine-tuning/output/got-ocr2/v2-20241021-161234/checkpoint-1000'目录结构
drwxr-xr-x 3 root root     4096 10月 21 17:17 ./
drwxr-xr-x 6 root root     4096 10月 21 17:08 ../
-rw-r--r-- 1 root root      713 10月 21 16:52 adapter_config.json
-rw-r--r-- 1 root root 15248512 10月 21 16:52 adapter_model.safetensors
-rw-r--r-- 1 root root       67 10月 21 16:52 additional_config.json
-rw-r--r-- 1 root root      286 10月 21 16:52 configuration.json
-rw-r--r-- 1 root root      143 10月 21 16:52 generation_config.json
drwxr-xr-x 2 root root     4096 10月 21 17:19 infer_result/
-rw-r--r-- 1 root root 30692296 10月 21 16:52 optimizer.pt
-rw-r--r-- 1 root root     5116 10月 21 16:52 README.md
-rw-r--r-- 1 root root    14244 10月 21 16:52 rng_state.pth
-rw-r--r-- 1 root root     1064 10月 21 16:52 scheduler.pt
-rw-r--r-- 1 root root    10720 10月 21 16:52 sft_args.json
-rw-r--r-- 1 root root    56224 10月 21 16:52 trainer_state.json
-rw-r--r-- 1 root root     7288 10月 21 16:52 training_args.bin

**Comment by santosh-gkg** [comment]
were you able to resolve this issue? please let me know i am facing the same issue

**Comment by wayne7412** [comment]
were you able to resolve this issue? please let me know i am facing the same issue

**Comment by evanlin88** [comment]
> were you able to resolve this issue? please let me know i am facing the same issue

@santosh-gkg 

Yes，pls use the “swift export” to merge the lora model，after that start up the model as normal；Don't use PeftModel to start up

the command like this：
CUDA_VISIBLE_DEVICES=1 swift export  \
    --ckpt_dir /data/got-ocr/swift-fine-tuning/output/got-ocr2/v0-20241022-163648/checkpoint-1000/ \
       --merge_lora true
