### ISSUE TITLE
在LSVT_full weak数据集上进行测试，错误不少啊

### ISSUE THREAD

**Issue by mathCrazyy** [Ucas-HaoranWei/GOT-OCR2.0#156]
如题，模式format比ocr好一些，但依然比较差呀。是还有别的操作嘛

**Comment by Ucas-HaoranWei** [comment]
1.这个数据集你训了吗？
2.你用的什么评测？

**Comment by mathCrazyy** [comment]
没有训练，是需要再额外训练嘛。
没有做严格的评测，本意不是去做评测。是想在工程中，用来筛选低质量数据呢，确实能够筛掉一些模糊不清的图片，但是对于高曝光、倾斜之类的图片，识别不太好，存在误删的情况，和paddleocr v4的模型相比，在少量数据上观察paddleocr好一些。

**Comment by Ucas-HaoranWei** [comment]
得训练呀，且不知道你看过论文没有，所有用来训练的自然图像都是paddleocr打的伪标签，paddleocr的结果就是真值，有部分能超越还是说明潜力大的，如果有高质量gt去微调下，性能肯定会提升

**Comment by mathCrazyy** [comment]
明白了谢谢啦，哎没有看过论文，我补补吧。
