### ISSUE TITLE
Nougat weights are CC-BY-NC

### ISSUE THREAD

**Issue by staghado** [Ucas-HaoranWei/GOT-OCR2.0#158]
I don't see how can the weights be [apache-2.0](https://huggingface.co/stepfun-ai/GOT-OCR2_0) while some of the data used to train the model is CC-BY-NC(the Nougat subset for example). 
Thanks for your clarification.

**Comment by Ucas-HaoranWei** [comment]
1. We do not use the Nougat weights and data. 
2. Are the data of Nougat  open-source？ To my knowledge,  they don't have open source the data, so it's impossible to use them.
3. We drew inspiration from Nougat's approach to processing LaTeX data and created data for training GOT.
4. The data we use for training is completely different from nougat, and the format we process is mathpix format.

**Comment by staghado** [comment]
thanks for the clarification.
I was confused and thought Nougat was used for the annotation. it’s clearer
now.
great work!
