### ISSUE TITLE
How to format training data for fine-tuning phase? One image has multiple contents.

### ISSUE THREAD

**Issue by thanhhuynhk17** [Ucas-HaoranWei/GOT-OCR2.0#159]
![image](https://github.com/user-attachments/assets/73e6011b-ef79-4952-ba9a-d6c0f19521f0)
Is using "\n" enough to separate multiple pieces of content in one image, or should it be cropped into multiple images?

Can I feed the model with the data below?
```
 {
   "query": ...,
   "images": ...,
   "response": "More than a simple option\nSimply a new choice for your McCombo\nTo learn more visit www.mcdonalds.com\nI'm lovin' it'\nAdvertisement Review Example"
   ...
 },
```

**Comment by thanhhuynhk17** [comment]
thank you

**Comment by SidneyRey** [comment]
Does the query in the data have practical significance?
