### ISSUE TITLE
简单测试了下

### ISSUE THREAD

**Issue by liwenju0** [Ucas-HaoranWei/GOT-OCR2.0#2]
### 测试图片
![page_54](https://github.com/user-attachments/assets/9d5e35ef-b906-4937-a529-086381c6eb49)
### 使用ocr 的结果：
**将 材 料 A 的 洋
菜 粉 、 果 冻 粉
拌 匀 ， 加 入 水 拌
匀，放置炉火煮
至糖溶化。**
将材料B的山楂与
洛神花洗净后与水
一同放入锅中，煮
沸后转小火继续煮
约10分钟，把山楂
与洛神花过滤掉。
1
**将 材 料 A 的 洋
菜 粉 、 枱 冻 粉
拌 匀 ， 加 入 水 拌 匀 ，
过 置 炉 火 煮
至糖溶化。**
2
再将白豆沙剥小
块加入，用小火
边搅拌边煮至完
全融合没有豆沙
块后熄火。
Point
若有 浮 沫 需 捞
除 ， 煮 至 豆 沙
呈稠糊状即可。
糕 ， 点 ， 笔 ， 记
◆在盘中铺保鲜膜，可使凝固
后的二珍糕较容易取出。
3
倒入铺好保鲜膜
的耐热方盘中，
待凉。
4
待稍凉未结冻前，
慢慢倒入作法3的
上面。
Point
可试滴1～2滴至盘
中，可呈凝固状态
即可，若不凝结表
示火候不足，须继
续煮至可凝固状
态。
5
将材料B的冰糖、
洋菜粉、果冻粉拌
匀，加入过滤好的
汤汁，再煮至糖溶
化后熄火。
7
待冷却后，移入
冰箱冷藏1～2小
时，冰凉后连同
保鲜膜提出，切
块即可食用。
6
A 白豆沙
600克
洋菜粉
4克
果冻粉
2克
水
600毫升
5
水
100克
洋菜粉
8克
果冻粉
4克
600毫升
4克
600毫升
4克
7
47

### 使用format的结果：

将材料 \(A\) 的 洋 菜粉、果 冻粉 拌匀, 加入水拌 匀, 放置炉火煮 至糖溶化。
再将白豆沙剥小 块加入, 用小火 边搅拌边煮至完 全融合没有豆沙 块后熄火。
\section*{Point}
若有浮沫需捞 除, 煮至豆沙 呈稠糊状即可。

\section*{二珍糕}
\section*{分题・长24厘米 \(\times\) 宽20厘米 \(\times\) 高5厘米方盘1盘}
\section*{结素粠・密封冷藏3天}
\section*{材料}
A 白豆沙 ………………600克
洋菜粉…………………4 克
果冻粉………………2 克
水…………………600毫升
B 山楂…………………20克
洛神花………………15克
水…………………600毫升
冰糖………………100克
洋菜粉………………8克
果冻粉………………4克
\section*{4}
将材料B的山楂与 洛神花洗净后与水 一同放入锅中, 煮 沸后转小火继续煮 约10分钟, 把山楂 与洛神花过滤掉。
\section*{4}
待稍凉未结冻前, 慢慢倒入作法3的 上面。
\section*{Point}
可试滴1 2滴至盘
中, 可呈凝固状态 即可, 若不凝结表 示火候不足, 须继 续煮至可凝固状 态。
\section*{5}
将材料B的冰糖、 洋菜粉、果冻粉拌 匀, 加入过滤好的 汤汁, 再煮至糖溶 化后熄火。
\section*{7}
待冷却后, 移入 冰箱冷藏1 2 小 时, 冰凉后连同 保鲜膜提出, 切 块即可食用。

### 结论
目前看，应该仅限于学术探索阶段，离生产距离还比较远

**Comment by Ucas-HaoranWei** [comment]
非常感谢反馈， 本项目只能用于学术研究，另外模型训练资源，数据都非常有限，这种分块的咱们图没有，后面更新版本的话我会尽力收集

**Comment by SidneyRey** [comment]
已经很棒了，很不错的数据驱动思路。
