### ISSUE TITLE
无字的图片输出不符合预期

### ISSUE THREAD

**Issue by Rheelt** [Ucas-HaoranWei/GOT-OCR2.0#212]
<img width="1062" alt="截屏2024-11-13 01 15 19" src="https://github.com/user-attachments/assets/414d2c63-c2ac-4cc4-8ed0-1be3c4b9716c">
如上图所示，无字的图片会输出
38
— CHRISTMAS COLLECTION 2021 —
请问这是什么问题？

**Comment by Ucas-HaoranWei** [comment]
哈哈，没有负样本训练，以为你这是个文档封皮，幻觉了吧，可以加入负样本微调

**Comment by Rheelt** [comment]
好的，看来需要微调一下了。
