### ISSUE TITLE
六群验证码过期了

### ISSUE THREAD

**Issue by wkml** [Ucas-HaoranWei/GOT-OCR2.0#214]
可以拉一下新群吗，谢谢！

**Comment by Ucas-HaoranWei** [comment]
https://github.com/Ucas-HaoranWei/GOT-OCR2.0/blob/main/assets/wechat6-2.jpg
新二维码

**Comment by wkml** [comment]
Hello, I have received your email.

**Comment by phooyao** [comment]
超过200人了，二维码加不了了
