### ISSUE TITLE
咨询，是否有完成从qwen2-vl-0.5B升级到qwen2-vl-7B的经验分享一下，谢谢

### ISSUE THREAD

**Issue by evanlin88** [Ucas-HaoranWei/GOT-OCR2.0#216]
GOT-OCR2.0  使用 ViTDet-80M 和Qwen-0.5B，是否除了升级Qwen2-vl-7B外，还需升级ViTDet？

**Comment by Ucas-HaoranWei** [comment]
不需要吧，换7B感觉也没必要，太大了吧

**Comment by evanlin88** [comment]
> 不需要吧，换7B感觉也没必要，太大了吧

因为试用了qwen2-vl-7b的ocr识别功能，感觉不错，但速度是慢了，本来想用7B的样本量来提升识别能力。目前自己造的样本量，质量和数量都不高，才几千张，

**Comment by xlg-go** [comment]
> > 不需要吧，换7B感觉也没必要，太大了吧
> 
> 因为试用了qwen2-vl-7b的ocr识别功能，感觉不错，但速度是慢了，本来想用7B的样本量来提升识别能力。目前自己造的样本量，质量和数量都不高，才几千张，

https://github.com/Ucas-HaoranWei/GOT-OCR2.0/issues/217

您好，请教一下，这个ocr纠错你遇到过吗？

**Comment by evanlin88** [comment]
> > > 不需要吧，换7B感觉也没必要，太大了吧
> > 
> > 
> > 因为试用了qwen2-vl-7b的ocr识别功能，感觉不错，但速度是慢了，本来想用7B的样本量来提升识别能力。目前自己造的样本量，质量和数量都不高，才几千张，
> 
> #217
> 
> 您好，请教一下，这个ocr纠错你遇到过吗？

我这边微调后的效果也会有纠错的，哈，识别：I have apple

**Comment by l1006986533** [comment]
我也有同样的想法，因为我遇到的有个任务(kie, key-information extraction) 不只是ocr识别，还要带着ocr的结果（包括位置信息）进行问答，比如，给出一张表，问：表的标题是什么？
GOT-OCR对于纯粹的ocr任务效果非常好，但无法进行问答。因此我想问一下，如果我既要用GOT-OCR的强大识别效果，又要用qwen 7b的强大问答能力，我应该怎么做？

**Comment by l1006986533** [comment]
@Ucas-HaoranWei 很抱歉打扰您，大佬可以看一下这个问题吗？
