### ISSUE TITLE
Test inference of fine-tuned GOT without using ms-swift

### ISSUE THREAD

**Issue by ep0p** [Ucas-HaoranWei/GOT-OCR2.0#222]
I have completed fine-tuning GOT using ms-swift and followed the steps to merge checkpoints with lora, among others. I have also reviewed the best practices outlined in [#2122](https://github.com/modelscope/ms-swift/issues/2122) 

However, it is unclear to me how to perform inference without going through ms-swift.

**Comment by ep0p** [comment]
The only way that i could find would be by uploading the model to hf.

**Comment by ep0p** [comment]
@MuatazMohammed first you need to create your dataset, then fine-tune, at the end you will have something that looks like this:
![image](https://github.com/user-attachments/assets/13560eec-b562-4572-b3e8-dd8fd1ba3ba2) 

i have got the merged checkpoint by doing :
` swift merge-lora --ckpt_dir /home/epop/ms-swift/output/got-ocr2/v80-20241123-093213/checkpoint-12300 `

after that i had to pass by hugging face, that means i created a model on hf interface, then uploaded the model i had under the merged folder to hf
![image](https://github.com/user-attachments/assets/e7ef2c2c-2813-4a56-9296-43e0da300904)

and then i used it like this in my code:
```
def load_got_model():
    tokenizer = AutoTokenizer.from_pretrained('elenapop/got_whole_page_tune_epoch_100', trust_remote_code=True)
    model = AutoModel.from_pretrained(
        'elenapop/got_whole_page_tune_epoch_100', 
        trust_remote_code=True, 
        low_cpu_mem_usage=True, 
        device_map='cuda', 
        use_safetensors=True
    ).eval().cuda()
    return model, tokenizer
```

**Comment by bhavyajoshi-mahindra** [comment]
Is there any way to load this model without uploading it it HF?

**Comment by ep0p** [comment]
The only one that i could find, besides hf, is by using the 'push_to_hub' parameter in SftArguments. But that will make you use ms hub instead of hf.

**Comment by enrico310786** [comment]
> [@MuatazMohammed](https://github.com/MuatazMohammed) first you need to create your dataset, then fine-tune, at the end you will have something that looks like this: ![image](https://github.com/user-attachments/assets/13560eec-b562-4572-b3e8-dd8fd1ba3ba2)
> 
> i have got the merged checkpoint by doing : `swift merge-lora --ckpt_dir /home/epop/ms-swift/output/got-ocr2/v80-20241123-093213/checkpoint-12300`
> 
> after that i had to pass by hugging face, that means i created a model on hf interface, then uploaded the model i had under the merged folder to hf ![image](https://github.com/user-attachments/assets/e7ef2c2c-2813-4a56-9296-43e0da300904)
> 
> and then i used it like this in my code:
> 
> ```
> def load_got_model():
>     tokenizer = AutoTokenizer.from_pretrained('elenapop/got_whole_page_tune_epoch_100', trust_remote_code=True)
>     model = AutoModel.from_pretrained(
>         'elenapop/got_whole_page_tune_epoch_100', 
>         trust_remote_code=True, 
>         low_cpu_mem_usage=True, 
>         device_map='cuda', 
>         use_safetensors=True
>     ).eval().cuda()
>     return model, tokenizer
> ```


once you have the model in Hugging Face, how do you call it and run inference on a single image? Can you share the script you use?

**Comment by ep0p** [comment]
you can run it like this:

```got_model, got_tokenizer = load_got_model()
res = got_model.chat(got_tokenizer, image_path, ocr_type='ocr')
```

as ocr_type you can use 'format' as well:

```
if got_mode == "plain texts OCR":
            res = got_model.chat(got_tokenizer, image_path, ocr_type='ocr')

        elif got_mode == "format texts OCR":
            res = got_model.chat(got_tokenizer, image_path, ocr_type='format', render=True, save_render_file=result_path)

        elif got_mode == "plain multi-crop OCR":
            res = got_model.chat_crop(got_tokenizer, image_path, ocr_type='ocr')

        elif got_mode == "format multi-crop OCR":
            res = got_model.chat_crop(got_tokenizer, image_path, ocr_type='format', render=True, save_render_file=result_path)
```
