### ISSUE TITLE
demo识别有的图片时效果不好

### ISSUE THREAD

**Issue by meng0423** [Ucas-HaoranWei/GOT-OCR2.0#228]
![image](https://github.com/user-attachments/assets/3fc22cb2-c2a7-4537-83a2-6935aef2974e)
如图所示

**Comment by Ucas-HaoranWei** [comment]
![image](https://github.com/user-attachments/assets/c87d1e3b-1675-4f68-b243-7ec385f8c384)
这种长条的两边留白不能太多

**Comment by meng0423** [comment]
> ![image](https://private-user-images.githubusercontent.com/50487563/390643966-c87d1e3b-1675-4f68-b243-7ec385f8c384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzE3MDAsIm5iZiI6MTczMjc3MTQwMCwicGF0aCI6Ii81MDQ4NzU2My8zOTA2NDM5NjYtYzg3ZDFlM2ItMTY3NS00ZjY4LWIyNDMtN2VjMzg1ZjhjMzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMmFhMTk5NzcyNGUwZWY5MTFkNmRjNzFjMzY4MTRhM2JiNTEwMWEzZjlkNjYzYzIyMTdiYWY1Y2JlNzU4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ifupp06fYNp_GD6B1EN7Sop6Tr689SDVYxWh9tyzmcc) 这种长条的两边留白不能太多

明白了，感谢回复
