### ISSUE TITLE
Pre-training Vision encoder

### ISSUE THREAD

**Issue by cryingjin** [Ucas-HaoranWei/GOT-OCR2.0#229]
Hello, I have a question about the image encoder. 

According to the paper, the image encoder was trained using the **VitDet** backbone. However, when I checked the repository mentioned in the readme for pretraining, I found that it contains models trained with **SAM** (presumably Meta's) and **OPT-125**. Where can I find references for VitDet pretraining?

**Comment by Ucas-HaoranWei** [comment]
Hi， the main-body of the encoder structure follows VitDet, the pretrain weights are unnecessary in our experiments. SAM is also based on VitDet.
