### ISSUE TITLE
对Structured data的识别效果很差

### ISSUE THREAD

**Issue by Cassieyy** [Ucas-HaoranWei/GOT-OCR2.0#23]
感谢您的工作，在试用中发现对格式非常单一、分辨率很高的表格识别效果非常不好。请问有什么可以调整的参数吗

command:
python3 GOT/demo/run_ocr_2.0.py  --model-name  ./GOT_weights/  --image-file /knt/pengyue.lpy/premium_table_parsing/imgs/split_27.png  --type format --render

![badcase](https://github.com/user-attachments/assets/1442d5f6-b183-4ebe-a4a5-0665b3a1eac2)

![badcase1](https://github.com/user-attachments/assets/8821ca39-e948-4f51-b8c3-fdb4b7b67a06)

**Comment by Ucas-HaoranWei** [comment]
如果觉得是分辨率高的问题，需要使用run crop，但是我看你这个的分辨率不高，只需要用你的数据稍加fine tune即可，我训练的表格数据极少

**Comment by Cassieyy** [comment]
谢谢您的耐心答复，我试下。

**Comment by Cassieyy** [comment]
顺便请问一下，我想让模型直接输出带html格式的字符串（原文输出的是latex格式），finetune 时的 value 可以直接给 html 代码吗。

**Comment by Ucas-HaoranWei** [comment]
是的，可以加微信群，群里有个大佬基于这套框架finetune的html表格，效果非常好，可以找他详细问问

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~
