### ISSUE TITLE
How to Train a GOT OCR 2.0 Model on a YOLO Dataset?

### ISSUE THREAD

**Issue by chelsea1212** [Ucas-HaoranWei/GOT-OCR2.0#246]
I am trying to train a GOT OCR 2.0 model using a YOLO dataset. The dataset is structured as follows:

It includes a data.yaml file.
There are separate train, test, and valid folders, each containing:
--An images folder with the image files.
--A labels folder with .txt files.
Could you please provide guidance or instructions on how to adapt this dataset for training the GOT OCR 2.0 model?

Thank you!

**Comment by xsank** [comment]
mark
