### ISSUE TITLE
latex识别怎么转成公式查看？看着效果一般

### ISSUE THREAD

**Issue by lonngxiang** [Ucas-HaoranWei/GOT-OCR2.0#37]
![image](https://github.com/user-attachments/assets/9a0dedfa-f27d-49b1-98e8-beb7dce70104)

![image](https://github.com/user-attachments/assets/6a405ea5-1b60-4dc5-993e-b74ff2cbf18f)

![image](https://github.com/user-attachments/assets/375b92f7-a4b0-4bfa-9217-bcbd54aac157)

**Comment by Ucas-HaoranWei** [comment]
--render 使用html查看，不是latex格式

**Comment by lonngxiang** [comment]
> --render 使用html查看，不是latex格式

用的transformers运行的呢，怎么使用？

**Comment by lonngxiang** [comment]
看到了，可以每个案例有说明和图像参考，用的transformers
