### ISSUE TITLE
有gradio gui吗

### ISSUE THREAD

**Issue by XJF2332** [Ucas-HaoranWei/GOT-OCR2.0#43]
暂时还没部署，想知道这个仓库有gui程序吗，如果没有的话将来会考虑做一个吗

**Comment by Ucas-HaoranWei** [comment]
huggingface有，后面有带宽可能做一个使用更方便的

**Comment by basicbh** [comment]
咋做gui，如果有方法我愿意学习制作

**Comment by XJF2332** [comment]
> 咋做gui，如果有方法我愿意学习制作

就是gradio，如果没有的话我也打算自己写一个来着

**Comment by XJF2332** [comment]
自己写了一个UI，欢迎来看看！
https://github.com/XJF2332/GOT-OCR-2-GUI
