### ISSUE TITLE
这个项目只能在 linux 下运行吧？

### ISSUE THREAD

**Issue by hjonline** [Ucas-HaoranWei/GOT-OCR2.0#46]
看到项目依赖的 deepspeed 安装出错，我查了下原来它只能在 linux 下安装，所以请在项目说明里加上这一点，以免其他人产生误解。

**Comment by facegbd** [comment]
直接去https://www.piwheels.org/project/deepspeed/  下载编译好的12.3 whl，安装之后就可以进行下去了。

**Comment by Carrie-L** [comment]
我在windows部署成功了

**Comment by xxss0903** [comment]
> 我在windows部署成功了

老哥，能出一个再windows部署的教程吗，谢谢了

**Comment by qiuwenbo1** [comment]
Windows上测试可以，手动装上面老哥说的deepspeed就行
https://github.com/Ucas-HaoranWei/GOT-OCR2.0/issues/46#issuecomment-2354456370

**Comment by hjonline** [comment]
手动安装deepspeed可行，我现在能运行ocr出结果，但是我需要知道到底有哪些命令行参数可用。
