### ISSUE TITLE
what languages are supported?

### ISSUE THREAD

**Issue by santosh-gkg** [Ucas-HaoranWei/GOT-OCR2.0#49]
Hello Everyone,
I wanted to know that what languages are supported by GOT-OCR2.0 and how can we train it on a language if it is not supported yet for example Hindi text.

**Comment by Ucas-HaoranWei** [comment]
Mainly support Chinese and English. For document OCR, GOT may support other languages, like Japanese, because the PDF data we crawled was not filtered thoroughly.  I think you only need to fine-tune the model if you need a new language feature.
