### ISSUE TITLE
表格识别效果一般

### ISSUE THREAD

**Issue by dafen12** [Ucas-HaoranWei/GOT-OCR2.0#53]

**Comment by Ucas-HaoranWei** [comment]
正常，一共用了20w表格数据，可以加群，有大佬用html 表格数据finetune了一个非常好的模型，想要提升效果需要在自己数据上微调

**Comment by CiaranYoung** [comment]
> 正常，一共用了20w表格数据，可以加群，有大佬用html 表格数据finetune了一个非常好的模型，想要提升效果需要在自己数据上微调

你好可以拉一下群吗，我看二维码过期了

**Comment by Lonepic** [comment]
> 正常，一共用了20w表格数据，可以加群，有大佬用html 表格数据finetune了一个非常好的模型，想要提升效果需要在自己数据上微调

您好，二维码好像过期了，还有就是目前有推荐的表格数据集嘛，比如img2latex或者img2html之类的数据集，因为我想进一步提升模型对表格的识别效果~
