### ISSUE TITLE
无法识别到文献中图片的题注等文字信息

### ISSUE THREAD

**Issue by zifengdexiatian** [Ucas-HaoranWei/GOT-OCR2.0#9]
1.如图，双栏文献中，正文识别能力很强，但是像图片的题注说明无法识别到，这是属于正常的吗？（我用传统OCR无法正确区分图5和图6的顺序，图5的题注给到了图6，张冠李戴，所以想测试GOT是否可以）
2. 另外想请问是否可以像其它ocr工具那样生成带有图片引用的markdown，这样可以进行完整的pdf文档转换。🙏🏻
![image](https://github.com/user-attachments/assets/70fd7cb6-b47f-4181-afc0-ede5dfd1e30d)

![image](https://github.com/user-attachments/assets/cc9589d9-62ca-4bc6-b9a4-5db7d1f7f7f9)

**Comment by Ucas-HaoranWei** [comment]
1. format对于页眉以及图内的信息，会跳过，很容易出现这种不识别，本质是把这部分文字当成图片跳过了，这是正常的，因为我们的数据合成的时候没法把图上的字也放进gt，用 --type ocr是可以解决的
2. 目前不支持检测图像加ref，这个可以使用自己的数据finetune下

**Comment by Ucas-HaoranWei** [comment]
这个问题是ocr把图像中的标注都给ocr，但是模型看不清导致重复了，试试run crop～

**Comment by zifengdexiatian** [comment]
> 这个问题是ocr把图像中的标注都给ocr，但是模型看不清导致重复了，试试run crop～
感谢回复，使用crop后一切正常了，并且效果非常好，如图，题注能够准确识别（之前无法识别发现是截图不完整，非常抱歉），然后化合物价态识别也非常准确（之前是剂量比识别有的不准，或者价态漏掉），用了这么多开源OCR，GOT是唯一发现能准确识别化合物上下角标的。
1. 如果方便是否可以简单介绍下crop是什么意思，功能是什么，为什么会有较大提升，稍后会拜读论文，很棒的工作
2. 另外目前发现，1080ti流式输出的速度比较慢，类似于本地的LLM（如llama3），换成更好的计算卡是否可以提速
![图片6](https://github.com/user-attachments/assets/fe0e3dec-edfa-4007-af4b-3821c655cd4e)
