### ISSUE TITLE
Loading finetuned model

### ISSUE THREAD

**Issue by bialykostek** [Ucas-HaoranWei/GOT-OCR2.0#93]
Hi, i've succesfully trained LoRA adapter, but I'm not sure how to load it correctly. For fine-tuning I've used:
```
CUDA_VISIBLE_DEVICES=0 swift sft --model_type got-ocr2 --model_id_or_path stepfun-ai/GOT-OCR2_0 --sft_type lora --dataset data.json
```
Fine tunning proceeded correctly. I tried to load it with PERF but it throws not supported error.  Modified `GOT/demo/run_ocr_2.0.py` file:
```
model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643).eval()
model = PeftModel.from_pretrained(model, "/root/checkpoint")
```
Can you provide simple example how to load it correcly?
Thanks

**Comment by evanlin88** [comment]
ValueError: Unrecognized configuration class <class 'transformers_modules.got_ocr2.modeling_GOT.GOTConfig'> for this kind of AutoModel: AutoModelForCausalLM.

**Comment by wayne7412** [comment]
I encountered the same problem. When preparing to test the fine-tuned model, I suspected that it was an error in the data format. Did you solve it?

**Comment by katie312** [comment]
> Hi, 你好， I used this code for testing, it's a little bit messy but hope it will help我用这个代码进行测试，它有点混乱，但希望它会有所帮助
> 
> ```
> import torch
> import os
> from PIL import Image
> 
> from swift.tuners import Swift
> from swift.utils import (append_to_jsonl, get_logger, get_main, get_model_info, read_multi_line, seed_everything,
>                          show_layers)
> from swift.llm.utils import (DeployArguments, InferArguments, MediaTag, Template, get_additional_saved_files, get_dataset,
>                     get_model_tokenizer, get_template, inference, inference_stream, is_adapter, is_quant_model,
>                     sample_dataset, set_generation_config)
> from peft import PeftModel
> 
> 
> def load_image(image_file):
>     if image_file.startswith('http') or image_file.startswith('https'):
>         response = requests.get(image_file)
>         image = Image.open(BytesIO(response.content)).convert('RGB')
>     else:
>         image = Image.open(image_file).convert('RGB')
>     return image
> 
> 
> model, tokenizer = get_model_tokenizer(
>     "got-ocr2",
>     torch.float16,
>     {'device_map': 'cuda:0'},
>     model_id_or_path="stepfun-ai/GOT-OCR2_0",
>     revision="master",
>     quant_method=None)
> 
> model = PeftModel.from_pretrained(model, "/root/output/got-ocr2/v2-20241001-195553/checkpoint-2764", revision=None, adapter_name="defaut", inference_mode=True).eval()
> 
> model.to(device='cuda',  dtype=torch.float16)
> 
> template: Template = get_template(
>     'got_ocr2',
>     tokenizer,
>     'You should follow the instructions carefully and explain your answers in detail.',
>     None,
>     'delete',
>     model=model,
>     tools_prompt='react_en')
> 
> response, _ = inference(model, template, stream=False, verbose=True, query="<image>OCR:\n ", history=[], system="You should follow the instructions carefully and explain your answers in detail.", images=['/root/got/2.jpg'], truncation_strategy="delete")
> ```

Hi, May I know the running environment for this code? I'm also stuck at the inference stage after fine-tuning. I tried with the GOT env but it says peft version does't match.
